"""Add workflow execution tables

Revision ID: 7eb39e955576
Revises:
Create Date: 2025-11-06 13:47:24.996988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eb39e955576'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_executions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_thread_id'), 'workflow_executions', ['thread_id'], unique=True)
    op.create_table('agent_executions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_approvals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approval_point', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modified_data', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Create additional indexes for better query performance
    op.create_index('idx_workflow_user_id', 'workflow_executions', ['user_id'])
    op.create_index('idx_workflow_created_at', 'workflow_executions', ['created_at'])
    op.create_index('idx_agent_workflow_id', 'agent_executions', ['workflow_id'])
    op.create_index('idx_agent_name', 'agent_executions', ['agent_name'])
    op.create_index('idx_agent_status', 'agent_executions', ['status'])
    op.create_index('idx_agent_started_at', 'agent_executions', ['started_at'])
    op.create_index('idx_approval_workflow_id', 'human_approvals', ['workflow_id'])
    op.create_index('idx_approval_user_id', 'human_approvals', ['user_id'])
    op.create_index('idx_approval_point', 'human_approvals', ['approval_point'])
    op.create_index('idx_approval_decision', 'human_approvals', ['decision'])
    op.create_index('idx_approval_created_at', 'human_approvals', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop additional indexes
    op.drop_index('idx_approval_created_at', table_name='human_approvals')
    op.drop_index('idx_approval_decision', table_name='human_approvals')
    op.drop_index('idx_approval_point', table_name='human_approvals')
    op.drop_index('idx_approval_user_id', table_name='human_approvals')
    op.drop_index('idx_approval_workflow_id', table_name='human_approvals')
    op.drop_index('idx_agent_started_at', table_name='agent_executions')
    op.drop_index('idx_agent_status', table_name='agent_executions')
    op.drop_index('idx_agent_name', table_name='agent_executions')
    op.drop_index('idx_agent_workflow_id', table_name='agent_executions')
    op.drop_index('idx_workflow_created_at', table_name='workflow_executions')
    op.drop_index('idx_workflow_user_id', table_name='workflow_executions')

    # Drop tables
    op.drop_table('human_approvals')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_workflow_executions_thread_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    # ### end Alembic commands ###
